//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureStore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied data on clipboard for {0} seconds.
        /// </summary>
        public static string AddClipboardMessage {
            get {
                return ResourceManager.GetString("AddClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter master password to login.
        /// </summary>
        public static string AppLoginDlgTitle {
            get {
                return ResourceManager.GetString("AppLoginDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change master password.
        /// </summary>
        public static string AppPasswordChangeDlgTitle {
            get {
                return ResourceManager.GetString("AppPasswordChangeDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter master password to unlock.
        /// </summary>
        public static string AppUnlockDlgTitle {
            get {
                return ResourceManager.GetString("AppUnlockDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied data removed from clipboard.
        /// </summary>
        public static string ClearClipboardMessage {
            get {
                return ResourceManager.GetString("ClearClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Data.
        /// </summary>
        public static string CopyTooltip {
            get {
                return ResourceManager.GetString("CopyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database data decryption is not successful.
        /// </summary>
        public static string DbDataDecryptionError {
            get {
                return ResourceManager.GetString("DbDataDecryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database data encryption is not successful.
        /// </summary>
        public static string DbDataEncryptionError {
            get {
                return ResourceManager.GetString("DbDataEncryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data.
        /// </summary>
        public static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data.
        /// </summary>
        public static string EditSecureDataDlgTitle {
            get {
                return ResourceManager.GetString("EditSecureDataDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data.
        /// </summary>
        public static string EditTooltip {
            get {
                return ResourceManager.GetString("EditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Data.
        /// </summary>
        public static string EncryptedData {
            get {
                return ResourceManager.GetString("EncryptedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid master password.
        /// </summary>
        public static string InvalidMasterKey {
            get {
                return ResourceManager.GetString("InvalidMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master key is changed. Do you want to save data before exit?.
        /// </summary>
        public static string MasterKeyChange {
            get {
                return ResourceManager.GetString("MasterKeyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and old password are same!.
        /// </summary>
        public static string NewAndOldPasswordsSame {
            get {
                return ResourceManager.GetString("NewAndOldPasswordsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data.
        /// </summary>
        public static string NewSecureDataDlgTitle {
            get {
                return ResourceManager.GetString("NewSecureDataDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be of min. 8 characters with at least one capital letter, one small letter, one number &amp; one special symbol.
        /// </summary>
        public static string PasswordComplexityError {
            get {
                return ResourceManager.GetString("PasswordComplexityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirmed password are not same!.
        /// </summary>
        public static string PasswordPairNotSame {
            get {
                return ResourceManager.GetString("PasswordPairNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Store.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Secret.
        /// </summary>
        public static string ShowSecret {
            get {
                return ResourceManager.GetString("ShowSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\r\n\r\n{1}.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
